In [8]:
n = int(input())
for i in range(n):
    print("  "*(n-i-1)+ "* "*(i+1))
for j in range(n-1):
    print("  "*(j+1)+"* "*(n-j-1))

10
                  * 
                * * 
              * * * 
            * * * * 
          * * * * * 
        * * * * * * 
      * * * * * * * 
    * * * * * * * * 
  * * * * * * * * * 
* * * * * * * * * * 
  * * * * * * * * * 
    * * * * * * * * 
      * * * * * * * 
        * * * * * * 
          * * * * * 
            * * * * 
              * * * 
                * * 
                  * 


## Memory

In [9]:
ls = [1,2,3,4]

In [10]:
type(ls)

list

In [24]:
# Total memory that is required by ls to save the data into your memory
import sys

print(sys.getsizeof(4), "Bytes")
print("Total Memory consumption by a list (ls) is {} Bytes".format(sys.getsizeof(1)*len(ls)))

28 Bytes
Total Memory consumption by a list (ls) is 112 Bytes


### 1Byte = 8Bits

## NumPy Array

In [17]:
# External Package : Import this
import numpy as np
# np.function_name

In [18]:
# Convert list ls into NumPy array
np_1 = np.array(ls)

In [19]:
type(np_1)

numpy.ndarray

In [20]:
np_1

array([1, 2, 3, 4])

In [21]:
# itemsize will return you the memory consumed by 1 element in your np_1 numpy array, in Bytes
np_1.itemsize

4

In [22]:
np_1.size

4

In [23]:
print("Total memeory consumption by np_1 is {} Bytes".format(np_1.itemsize*np_1.size))

Total memeory consumption by np_1 is 16 Bytes


## Lists: Pre-defined IDS(Pointers)
## NumPy Array: Id is assigned on fly

- is: identity comparison
- ==: equality comparison

In [27]:
ls

[1, 2, 3, 4]

In [28]:
np_1

array([1, 2, 3, 4])

In [39]:
ls[0] is ls[0]

True

In [34]:
np_1[0] is np_1[0]

False

In [40]:
np_1[0] ==np_1[0]

True

## Speed

In [44]:
import time

ls1 = [i for i in range(1000000)]
np_ar1 = np.array(ls1)

# Add 2 to each element of a list
t1 = time.time()
ls2 = [i+2 for i in ls1]
t2 = time.time()

print("Time taken by List operation : {} ms".format((t2-t1)*1000))

# NumPy operation
t1 = time.time()
np_ar2 = np_ar1+2
t2 = time.time()

print("Time taken by NumPy operation : {} ms".format((t2-t1)*1000))

Time taken by List operation : 209.14077758789062 ms
Time taken by NumPy operation : 5.003690719604492 ms


## Working with NumPy

In [45]:
# How to create a NumPy Array

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [47]:
np_1
# Rank-1 NumPy Array

array([1, 2, 3, 4])

In [49]:
# NumPy can be 1-D, 2-D, 3-D, n-D
# 2-D NumPy Array

np_2 = np.array([[1,2,3,4], [5,6,7,8]])

In [50]:
np_2.shape
# Two Rows
# 4 columns

(2, 4)

In [51]:
np_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
# 3-D NumPy

# Load a image
import cv2

img = cv2.imread("mother_teresa.jpg")

In [54]:
img.shape

(600, 640, 3)

## Inspecting a NumPy Array

In [57]:
# Dimension
img.ndim

3

In [58]:
# Shape
img.shape
#(Number of rows, Number of Columns, Number of Layers)

(600, 640, 3)

In [59]:
# Size
img.size
# Total elements in my array

1152000

In [61]:
np_1.size

4

In [62]:
np_1

array([1, 2, 3, 4])

In [63]:
# Data Type
img.dtype
# 8 bits ==1 Byte

dtype('uint8')

In [64]:
## Size of each element in a NumPy Array
img.itemsize
# Bytes

1

In [65]:
## Total size consumed by a NumPy Array
img.nbytes
# Bytes

1152000

## Working With NumPy Array

In [67]:
## Reshape
## To Convert a NumPy Array from one dimesion to another

np_1 =np.array([1,2,3,4,5,6,7,8,9])
np_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# 3*3
np_1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
## Lists: range()
## NumPy : arange()

[i for i in range(0,10, 2)]

[0, 2, 4, 6, 8]

In [72]:
# NumPy Array
np.arange(10, 100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [81]:
## Random

a = np.random.random((3,3))
a
# A NumPy array of the specified shape and the elements will be between 0-1 random

array([[0.16590209, 0.5248374 , 0.74846879],
       [0.58093652, 0.7399672 , 0.70924344],
       [0.2597585 , 0.30412022, 0.14805735]])

In [77]:
np.random.randint(0,100)
# It will return a random int between the sepcified range

47

In [78]:
np.random.randn(10)
# Random 10 element

array([-1.08333731, -0.19771031, -1.87705138, -0.4393507 , -1.28444498,
        0.68536496, -2.09794633, -0.34543012, -0.28745365, -0.17803901])

In [86]:
## Mean
np.mean(a, axis = 1)

array([0.47973609, 0.67671572, 0.23731202])

In [87]:
np.mean(a, axis = 0)

array([0.33553237, 0.52297494, 0.53525653])

In [88]:
np.mean(a)

0.4645879444144872